const operacoes = require("./calc")

console.log(operacoes.soma(1, 5))
console.log(operacoes.subtracao(1, 5))
console.log(operacoes.multiplicação(1, 5))
console.log(operacoes.divi(6, 2))
console.log(operacoes.bhaskara(2, 4, 6))
console.log(operacoes.teoremaPit(2, 8))
console.log(operacoes.circulo(6))
console.log(operacoes.cubo(6))
console.log(operacoes.cilindro(6, 8))